---
- name: show value of variable myvar
  hosts: desktop
  gather_facts: false

  vars:
    myvar: "from playbook vars section"

  vars_prompt:
    - name: myvar
      prompt: "enter value for myvar: "
      private: false

  vars_files:
    - myvars.yml

  roles:
    - role: student.testrole
...
